### ISSUE TITLE
NewOrder Lambda failed to begin subsegment named 'dynamodb': segment cannot be found

### ISSUE THREAD

**Issue by BastLeblanc** [aws-samples/aws-step-functions-long-lived-transactions#1]
Hi,

After deploying the cloud formation template.
Created a simple Step Functions:

`{
  "Comment": "re:Invent 2018 Builder Session - Managing Long Lived Transactions with AWS Step Functions State Machine",
  "StartAt": "ProcessOrder",
  "States": {
    "ProcessOrder": {
      "Comment": "First transaction to save the order and set the order status to new",
      "Type": "Task",
      "Resource": "arn:aws:lambda:us-east-1:ACCOUNTID:function:NextGenOrderManagt-NewOrderFunction-xxxx",
      "TimeoutSeconds": 10,
      "Catch": [{
        "ErrorEquals": ["ErrProcessOrder"],
        "ResultPath": "$.error",
        "Next": "UpdateOrderStatusFailed"
      }],
            "Next": "UpdateOrderStatusSucceeded"
    },
        "UpdateOrderStatusFailed": {
      "Type": "Fail"
    },
    "UpdateOrderStatusSucceeded": {
      "Type": "Succeed"
    }
  }
}`

And it fails on the scenario 1:
`{
  "order_id": "1ae4501d-ed92-4b27-bf0e-fd978ed45127",
  "order_date": "2018-10-19T10:50:16+08:00",
  "customer_id": "8d04ea6f-c6b2-4422-8550-839a16f01feb",
  "items": [{
      "item_id": "987",
      "qty": 1.0,
      "description": "Cart item 1",
      "unit_price": 19.99
    },
    {
      "item_id": "546",
      "qty": 1.0,
      "description": "Cart item 2",
      "unit_price": 23.98
    },
    {
      "item_id": "3",
      "qty": 2.0,
      "description": "Cart item 3",
      "unit_price": 6.50
    }
  ]
}`

**with the error: `failed to begin subsegment named 'dynamodb': segment cannot be found`**

Full stack:
`{
  "errorMessage": "failed to begin subsegment named 'dynamodb': segment cannot be found.",
  "errorType": "string",
  "stackTrace": [
    {
      "path": "github.com/aws/aws-lambda-go@v1.7.0/lambda/function.go",
      "line": 27,
      "label": "(*Function).Invoke.func1"
    },
    {
      "path": "runtime/asm_amd64.s",
      "line": 522,
      "label": "call32"
    },
    {
      "path": "runtime/panic.go",
      "line": 513,
      "label": "gopanic"
    },
    {
      "path": "github.com/aws/aws-xray-sdk-go@v0.9.4/strategy/ctxmissing/default_context_missing.go",
      "line": 47,
      "label": "(*DefaultRuntimeErrorStrategy).ContextMissing"
    },
    {
      "path": "github.com/aws/aws-xray-sdk-go@v0.9.4/xray/segment.go",
      "line": 88,
      "label": "BeginSubsegment"
    },
    {
      "path": "github.com/aws/aws-xray-sdk-go@v0.9.4/xray/aws.go",
      "line": 52,
      "label": "glob..func1"
    },
    {
      "path": "github.com/aws/aws-sdk-go@v1.15.81/aws/request/handlers.go",
      "line": 213,
      "label": "(*HandlerList).Run"
    },
    {
      "path": "github.com/aws/aws-sdk-go@v1.15.81/aws/request/request.go",
      "line": 361,
      "label": "(*Request).Build"
    },
    {
      "path": "github.com/aws/aws-sdk-go@v1.15.81/aws/request/request.go",
      "line": 382,
      "label": "(*Request).Sign"
    },
    {
      "path": "github.com/aws/aws-sdk-go@v1.15.81/aws/request/request.go",
      "line": 490,
      "label": "(*Request).Send"
    },
    {
      "path": "github.com/aws/aws-sdk-go@v1.15.81/service/dynamodb/api.go",
      "line": 2936,
      "label": "(*DynamoDB).PutItemWithContext"
    },
    {
      "path": "new/main.go",
      "line": 68,
      "label": "saveOrder"
    },
    {
      "path": "new/main.go",
      "line": 45,
      "label": "handler"
    },
    {
      "path": "runtime/asm_amd64.s",
      "line": 527,
      "label": "call1024"
    },
    {
      "path": "reflect/value.go",
      "line": 447,
      "label": "Value.call"
    },
    {
      "path": "reflect/value.go",
      "line": 308,
      "label": "Value.Call"
    },
    {
      "path": "github.com/aws/aws-lambda-go@v1.7.0/lambda/handler.go",
      "line": 114,
      "label": "NewHandler.func1"
    },
    {
      "path": "github.com/aws/aws-lambda-go@v1.7.0/lambda/handler.go",
      "line": 22,
      "label": "lambdaHandler.Invoke"
    },
    {
      "path": "github.com/aws/aws-lambda-go@v1.7.0/lambda/function.go",
      "line": 59,
      "label": "(*Function).Invoke"
    },
    {
      "path": "runtime/asm_amd64.s",
      "line": 523,
      "label": "call64"
    },
    {
      "path": "reflect/value.go",
      "line": 447,
      "label": "Value.call"
    },
    {
      "path": "reflect/value.go",
      "line": 308,
      "label": "Value.Call"
    },
    {
      "path": "net/rpc/server.go",
      "line": 384,
      "label": "(*service).call"
    },
    {
      "path": "runtime/asm_amd64.s",
      "line": 1333,
      "label": "goexit"
    }
  ]
}`

**Comment by sliedig** [comment]
Hello @BastLeblanc, sorry for the delay, I've just returned from leave. Let me look into this and get back to you asap. Thanks.
