### ISSUE TITLE
Stacks not available via S3 - Access Denied

### ISSUE THREAD

**Issue by andrewbruno** [aws-samples/aws-step-functions-long-lived-transactions#2]
The setup documentation offers a recommended way to launch the stack, as per:

https://github.com/aws-samples/aws-step-functions-long-lived-transactions/blame/master/docs/setup.md#L9-L11

When attempting to access the stacks, I get Access Denied.

**Comment by sliedig** [comment]
@andrewbruno Apologies for that. The Public Access policies on the bucket were preventing access. Please try again.

**Comment by andrewbruno** [comment]
Thank you
