### ISSUE TITLE
Error deploying cloudformation stacks

### ISSUE THREAD

**Issue by Eman-1239** [aws-samples/aws-step-functions-long-lived-transactions#9]
When pressing the Launch Stack button (regardless of the region), the stack won't deploy anymore. Would be nice if it got resolved fast. Thank you.

**Comment by sliedig** [comment]
Working on a update as we speak 👍

**Comment by Eman-1239** [comment]
Do you know when the update is expected to be finalized?

**Comment by sliedig** [comment]
Just working on some additional fixes, and then will merge #10

**Comment by sliedig** [comment]
This is now resolved. Please review the lastest docs. Reopen this issue if you still have problems.
